import React from 'react';
import {
  AbsoluteFill,
  Audio,
  Sequence,
  staticFile,
  useVideoConfig,
} from 'remotion';
import { Closing } from '../components/Closing';
import { LowerThird } from '../components/LowerThird';
import { ScreencastSlot } from '../components/ScreencastSlot';
import { SCRIPT } from '../content/script';
import { palette } from '../theme/tokens';
import { Hook } from './Hook';

/**
 * 60-second master demo.
 *
 * Beat structure (mirrors docs/marketing.md § 60-Second Master Demo Script):
 *   0:00 – 0:03  Cold open  (dictation screencast, no narration)
 *   0:03 – 0:06  Hook       (programmatic, reuses Hook composition)
 *   0:06 – 0:22  Dictation  (screencast + lower-third + VO)
 *   0:22 – 0:38  Transcription (screencast + lower-third + VO)
 *   0:38 – 0:54  Meeting    (screencast + lower-third + VO)
 *   0:54 – 1:00  Closing    (programmatic close card + VO)
 *
 * Audio is per-scene, generated by `npm run voice`. Screencasts go in
 * `public/screencasts/` — until they're recorded, ScreencastSlot renders
 * a branded placeholder so this composition stays renderable.
 */
export const Demo60: React.FC = () => {
  const { fps } = useVideoConfig();

  const COLD_OPEN = fps * 3;
  const HOOK = fps * 3;
  const MODE = fps * 16;
  const CLOSE = fps * 6;

  return (
    <AbsoluteFill style={{ backgroundColor: palette.paper }}>
      {/* 0:00 – 0:03  Cold open dictation, no VO */}
      <Sequence from={0} durationInFrames={COLD_OPEN} name="Cold open">
        <ScreencastSlot
          src="cold-open.mp4"
          label="Cold Open"
          hint="Tight shot: hands on keyboard → Fn tap → dictation appearing live in Slack mid-thread."
        />
      </Sequence>

      {/* 0:03 – 0:06  Hook reveal */}
      <Sequence
        from={COLD_OPEN}
        durationInFrames={HOOK}
        name="Hook"
      >
        <Hook />
        <Audio
          src={staticFile('audio/hook-opener.wav')}
          startFrom={0}
        />
      </Sequence>

      {/* 0:06 – 0:22  Dictation mode */}
      <Sequence
        from={COLD_OPEN + HOOK}
        durationInFrames={MODE}
        name="Dictation"
      >
        <ScreencastSlot
          src={SCRIPT.modes.dictation.screencast.replace('screencasts/', '')}
          label={SCRIPT.modes.dictation.title}
          hint="Three quick app cuts: Slack thread → Cursor (code) → browser address bar. Each shows dictation working live."
        />
        <LowerThird text={SCRIPT.modes.dictation.caption} startFrame={36} />
        <Audio src={staticFile('audio/mode-dictation.wav')} />
      </Sequence>

      {/* 0:22 – 0:38  Transcription mode */}
      <Sequence
        from={COLD_OPEN + HOOK + MODE}
        durationInFrames={MODE}
        name="Transcription"
      >
        <ScreencastSlot
          src={SCRIPT.modes.transcription.screencast.replace('screencasts/', '')}
          label={SCRIPT.modes.transcription.title}
          hint="Three beats: drag MP4 → diarized transcript appears. Paste YouTube URL → transcribed in <60s. Click Export → format menu opens."
        />
        <LowerThird text={SCRIPT.modes.transcription.caption} startFrame={36} />
        <Audio src={staticFile('audio/mode-transcription.wav')} />
      </Sequence>

      {/* 0:38 – 0:54  Meeting recording mode */}
      <Sequence
        from={COLD_OPEN + HOOK + MODE * 2}
        durationInFrames={MODE}
        name="Meeting"
      >
        <ScreencastSlot
          src={SCRIPT.modes.meeting.screencast.replace('screencasts/', '')}
          label={SCRIPT.modes.meeting.title}
          hint="Pill recording state → live notes panel + transcript ticking → finished meeting in Library with AI summary."
        />
        <LowerThird text={SCRIPT.modes.meeting.caption} startFrame={36} />
        <Audio src={staticFile('audio/mode-meeting.wav')} />
      </Sequence>

      {/* 0:54 – 1:00  Closing card */}
      <Sequence
        from={COLD_OPEN + HOOK + MODE * 3}
        durationInFrames={CLOSE}
        name="Closing"
      >
        <Closing />
        <Audio src={staticFile('audio/closing.wav')} />
      </Sequence>
    </AbsoluteFill>
  );
};
